title: Trent Shea's University Blog
description: >-
  My blog during my Bachelor of Science Major in Computing and Information
  Systems at Athabasca University.
google_analytics: G-0YLH688ENN
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: facebook, user_url: "https://facebook.com/trentjshea" }
    - { platform: github, user_url: "https://github.com/trentshea" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/trentshea" }
    - { platform: twitter, user_url: "https://twitter.com/trentshea" }
